menu:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
