blog_homepage:
    path:     /blog
    defaults: { _controller: BlogBundle:Blog:index }
blog_hello: 
    path: /hello-world
    defaults: { _controller: BlogBundle:Blog:index }
blog_voir: 
     path: /blog/post/{id}
     defaults: { _controller: BlogBundle:Blog:voir }
blog_dernier: 
     path: /blog/post/dernier
     defaults: { _controller: BlogBundle:Blog:dernier }
blog_ajouter: 
    path: /blog/ajouter
    defaults: { _controller: BlogBundle:Blog:ajouter }
blog_contact: 
    path: /blog/contact
    defaults: { _controller: BlogBundle:Blog:contact }